# src/strings.py

STRINGS = {
    'ru': {
        'app_title': "Менеджер плавающих картинок",
        'ready': "✅ Готов к работе! H - скрыть/показать окна",
        'data_folder': "📁 Данные хранятся в:",
        'settings_updated': "✅ Настройки обновлены! Обычный зум: +{}%",
        'no_windows': "⚠️ Нет открытых окон",
        'windows_shown': "🪟 Показано {} окон",
        'windows_hidden': "👁️ Скрыто {} окон (нажмите H для показа)",
        'folder_opened': "📂 Открыта папка:",
        'folder_created': "📂 Папка создана и открыта:",
        'folder_error': "Не удалось открыть папку",
        'gallery_loaded': "📂 Загружено {} картинок из прошлого сеанса",
        'image_added': "✅ Добавлено {} картинок (всего: {})",
        'clipboard_added': "✅ Картинка из буфера добавлена и сохранена (всего: {})",
        'clipboard_error': "Не удалось вставить из буфера",
        'clipboard_no_image': "В буфере обмена нет изображения",
        'clipboard_not_image': "В буфере не изображение",
        'deleted': "🗑️ Удалено {} картинок (осталось: {})",
        'list_cleared': "📭 Список очищен",
        'select_images': "Выберите картинки для удаления",
        'select_from_list': "Выберите картинки из списка",
        'add_images_first': "Сначала добавьте картинки",
        'no_windows_arrange': "⚠️ Нет открытых окон для расположения",
        'arranged_cascade': "✅ {} окон расположены каскадом",
        'arranged_grid': "✅ {} окон расположены сеткой ({}x{})",
        'windows_opened': "🪟 Открыто окон: {}",
        'images_opened': "🪟 Открыто {} картинок",
        'all_closed': "✅ Все окна закрыты",
        'exiting': "Закрытие программы, сохраняем список...",
        'error_open_image': "Не удалось открыть изображение",
        'language_changed': "🌐 Язык изменен. Программа будет перезапущена.",

        # Подсказки для кнопок панели инструментов
        'tooltip_open': "Открыть (Ctrl+O)",
        'tooltip_paste': "Вставить из буфера (Ctrl+V)",
        'tooltip_show_selected': "Показать выбранные",
        'tooltip_show_all': "Показать все (Ctrl+A)",
        'tooltip_toggle_windows': "Скрыть/Показать все окна (H)",
        'tooltip_cascade': "Расположить каскадом",
        'tooltip_grid': "Расположить сеткой",
        'tooltip_close_all': "Закрыть все окна (Ctrl+W)",
        'tooltip_settings': "Настройки (F1)",
        'tooltip_app_folder': "Папка приложения",
        'tooltip_delete': "Удалить выбранные (Del)",
        'tooltip_clear_list': "Очистить весь список",
        'tooltip_exit': "Выход (Ctrl+Q)",

        # Меню
        'menu_file': "Файл",
        'menu_open': "Открыть картинки (Ctrl+O)",
        'menu_paste': "Вставить из буфера (Ctrl+V)",
        'menu_show_all': "Показать все (Ctrl+A)",
        'menu_close_all': "Закрыть все окна (Ctrl+W)",
        'menu_open_folder': "Открыть папку приложения",
        'menu_exit': "Выход (Ctrl+Q)",
        'menu_edit': "Правка",
        'menu_delete': "Удалить выбранные (Del)",
        'menu_clear': "Очистить список",
        'menu_view': "Вид",
        'menu_toggle_windows': "Скрыть/Показать все окна (H)",
        'menu_cascade': "Каскадом",
        'menu_grid': "Сеткой",
        'menu_settings': "Настройки",
        'menu_settings_item': "Настройки (Ctrl+S / F1)",
        'menu_reset_settings': "Сбросить настройки",
        'menu_help': "Помощь",
        'menu_shortcuts': "Горячие клавиши",
        'menu_about': "О программе",

        # Кнопки
        'btn_open': "📁 ОТКРЫТЬ (Ctrl+O)",
        'btn_paste': "📋 ВСТАВИТЬ (Ctrl+V)",
        'btn_show_selected': "🖼️ ПОКАЗАТЬ ВЫБР.",
        'btn_show_all': "✨ ПОКАЗАТЬ ВСЕ (Ctrl+A)",
        'btn_toggle': "👁️ СКРЫТЬ/ПОКАЗАТЬ (H)",
        'btn_close_all': "✖ ЗАКРЫТЬ ВСЕ (Ctrl+W)",
        'btn_settings': "⚙️ НАСТРОЙКИ (F1)",
        'btn_folder': "📂 ПАПКА ПРИЛОЖЕНИЯ",

        # Окно настроек
        'settings_title': "Настройки программы",
        'settings_window': "Окно",
        'settings_fullscreen': "На весь экран (F11)",
        'settings_close': "Закрыть (Esc)",
        'settings_main_title': "⚙️ НАСТРОЙКИ ПРОГРАММЫ",
        'settings_zoom_speed': "🎯 СКОРОСТЬ ЗУМА",
        'settings_slow_zoom': "Медленный зум (Ctrl + Колесо):",
        'settings_normal_zoom': "Обычный зум (Колесо):",
        'settings_fast_zoom': "Быстрый зум (Shift + Колесо):",
        'settings_zoom_limits': "📏 ОГРАНИЧЕНИЯ ЗУМА",
        'settings_min_zoom': "Минимальный зум:",
        'settings_max_zoom': "Максимальный зум:",
        'settings_animation': "🎬 АНИМАЦИЯ",
        'settings_zoom_animation': "Включить плавную анимацию зума",
        'settings_anim_duration': "Длительность анимации (мс):",
        'settings_ui': "🎨 ИНТЕРФЕЙС",
        'settings_hide_delay': "Задержка скрытия кнопок (мс):",
        'settings_border_size': "Размер границы окна (пикс):",
        'settings_language': "🌐 ЯЗЫК",
        'settings_language_label': "Выберите язык:",
        'settings_save': "💾 СОХРАНИТЬ",
        'settings_reset': "↺ СБРОСИТЬ",
        'settings_cancel': "❌ ОТМЕНА",
        'settings_saved': "Настройки сохранены!\nОни применятся к новым окнам.",
        'settings_reset_confirm': "Вы уверены, что хотите сбросить все настройки к стандартным?",
        'settings_reset_done': "Настройки сброшены к стандартным",

        # Окно картинки
        'img_loading': "🔄 Загрузка...",
        'img_path_copied': "✅ Путь скопирован",
        'img_zoom_reset': "✅ Зум сброшен",
        'img_window_reset': "✅ Окно сброшено к исходному состоянию",
        'img_mode_keep_aspect': "🔄 Режим: сохранение пропорций (фиксировано для зума)",
        'img_zoom_percent': "🔍 {}%",

        # Контекстное меню
        'ctx_zoom_in': "🔍 Увеличить (+)",
        'ctx_zoom_out': "🔍 Уменьшить (-)",
        'ctx_reset_window': "⟳ Сбросить окно",
        'ctx_keep_aspect': "📐 Сохранять пропорции (Ctrl+A)",
        'ctx_optimal_size': "📏 Оптимальный размер",
        'ctx_copy_path': "📋 Копировать путь",
        'ctx_close': "🗑️ Закрыть (Esc)",

        # О программе
        'about_title': "О программе",
        'about_text': "Текст о программе...",

        # Горячие клавиши
        'shortcuts_title': "Горячие клавиши",
        'shortcuts_text': "Текст горячих клавиш...",
    },
    'en': {
        'app_title': "Floating Images Manager",
        'ready': "✅ Ready! H - hide/show all windows",
        'data_folder': "📁 Data stored in:",
        'settings_updated': "✅ Settings updated! Normal zoom: +{}%",
        'no_windows': "⚠️ No open windows",
        'windows_shown': "🪟 {} windows shown",
        'windows_hidden': "👁️ {} windows hidden (press H to show)",
        'folder_opened': "📂 Folder opened:",
        'folder_created': "📂 Folder created and opened:",
        'folder_error': "Failed to open folder",
        'gallery_loaded': "📂 Loaded {} images from previous session",
        'image_added': "✅ Added {} images (total: {})",
        'clipboard_added': "✅ Image from clipboard added and saved (total: {})",
        'clipboard_error': "Failed to paste from clipboard",
        'clipboard_no_image': "No image in clipboard",
        'clipboard_not_image': "Clipboard content is not an image",
        'deleted': "🗑️ Deleted {} images (remaining: {})",
        'list_cleared': "📭 List cleared",
        'select_images': "Select images to delete",
        'select_from_list': "Select images from the list",
        'add_images_first': "Add images first",
        'no_windows_arrange': "⚠️ No open windows to arrange",
        'arranged_cascade': "✅ {} windows arranged in cascade",
        'arranged_grid': "✅ {} windows arranged in grid ({}x{})",
        'windows_opened': "🪟 Windows open: {}",
        'images_opened': "🪟 Opened {} images",
        'all_closed': "✅ All windows closed",
        'exiting': "Exiting, saving gallery...",
        'error_open_image': "Failed to open image",
        'language_changed': "🌐 Language changed. Program will restart.",

        # Tooltips for toolbar buttons
        'tooltip_open': "Open (Ctrl+O)",
        'tooltip_paste': "Paste from clipboard (Ctrl+V)",
        'tooltip_show_selected': "Show selected",
        'tooltip_show_all': "Show all (Ctrl+A)",
        'tooltip_toggle_windows': "Hide/Show all windows (H)",
        'tooltip_cascade': "Arrange cascade",
        'tooltip_grid': "Arrange grid",
        'tooltip_close_all': "Close all windows (Ctrl+W)",
        'tooltip_settings': "Settings (F1)",
        'tooltip_app_folder': "Application folder",
        'tooltip_delete': "Delete selected (Del)",
        'tooltip_clear_list': "Clear entire list",
        'tooltip_exit': "Exit (Ctrl+Q)",

        # Menu
        'menu_file': "File",
        'menu_open': "Open Images (Ctrl+O)",
        'menu_paste': "Paste from Clipboard (Ctrl+V)",
        'menu_show_all': "Show All (Ctrl+A)",
        'menu_close_all': "Close All Windows (Ctrl+W)",
        'menu_open_folder': "Open App Folder",
        'menu_exit': "Exit (Ctrl+Q)",
        'menu_edit': "Edit",
        'menu_delete': "Delete Selected (Del)",
        'menu_clear': "Clear List",
        'menu_view': "View",
        'menu_toggle_windows': "Hide/Show All Windows (H)",
        'menu_cascade': "Cascade",
        'menu_grid': "Grid",
        'menu_settings': "Settings",
        'menu_settings_item': "Settings (Ctrl+S / F1)",
        'menu_reset_settings': "Reset Settings",
        'menu_help': "Help",
        'menu_shortcuts': "Shortcuts",
        'menu_about': "About",

        # Buttons
        'btn_open': "📁 OPEN (Ctrl+O)",
        'btn_paste': "📋 PASTE (Ctrl+V)",
        'btn_show_selected': "🖼️ SHOW SELECTED",
        'btn_show_all': "✨ SHOW ALL (Ctrl+A)",
        'btn_toggle': "👁️ HIDE/SHOW (H)",
        'btn_close_all': "✖ CLOSE ALL (Ctrl+W)",
        'btn_settings': "⚙️ SETTINGS (F1)",
        'btn_folder': "📂 APP FOLDER",

        # Settings window
        'settings_title': "Program Settings",
        'settings_window': "Window",
        'settings_fullscreen': "Fullscreen (F11)",
        'settings_close': "Close (Esc)",
        'settings_main_title': "⚙️ PROGRAM SETTINGS",
        'settings_zoom_speed': "🎯 ZOOM SPEED",
        'settings_slow_zoom': "Slow zoom (Ctrl + Wheel):",
        'settings_normal_zoom': "Normal zoom (Wheel):",
        'settings_fast_zoom': "Fast zoom (Shift + Wheel):",
        'settings_zoom_limits': "📏 ZOOM LIMITS",
        'settings_min_zoom': "Minimum zoom:",
        'settings_max_zoom': "Maximum zoom:",
        'settings_animation': "🎬 ANIMATION",
        'settings_zoom_animation': "Enable smooth zoom animation",
        'settings_anim_duration': "Animation duration (ms):",
        'settings_ui': "🎨 INTERFACE",
        'settings_hide_delay': "Button hide delay (ms):",
        'settings_border_size': "Window border size (px):",
        'settings_language': "🌐 LANGUAGE",
        'settings_language_label': "Select language:",
        'settings_save': "💾 SAVE",
        'settings_reset': "↺ RESET",
        'settings_cancel': "❌ CANCEL",
        'settings_saved': "Settings saved!\nThey will apply to new windows.",
        'settings_reset_confirm': "Are you sure you want to reset all settings to defaults?",
        'settings_reset_done': "Settings reset to defaults",

        # Image window
        'img_loading': "🔄 Loading...",
        'img_path_copied': "✅ Path copied",
        'img_zoom_reset': "✅ Zoom reset",
        'img_window_reset': "✅ Window reset to original state",
        'img_mode_keep_aspect': "🔄 Mode: keep aspect ratio (fixed for zoom)",
        'img_zoom_percent': "🔍 {}%",

        # Context menu
        'ctx_zoom_in': "🔍 Zoom In (+)",
        'ctx_zoom_out': "🔍 Zoom Out (-)",
        'ctx_reset_window': "⟳ Reset Window",
        'ctx_keep_aspect': "📐 Keep Aspect Ratio (Ctrl+A)",
        'ctx_optimal_size': "📏 Optimal Size",
        'ctx_copy_path': "📋 Copy Path",
        'ctx_close': "🗑️ Close (Esc)",

        # About
        'about_title': "About",
        'about_text': "About text...",

        # Shortcuts
        'shortcuts_title': "Keyboard Shortcuts",
        'shortcuts_text': "Shortcuts text...",
    }
}